#!/bin/bash
mkdir $HOME/wine
echo PiBlox Studio Installer
cd $HOME/.piblox && wget https://www.dropbox.com/s/3pkparicmagolpf/wine.zip
cd $HOME/.piblox && wget https://www.dropbox.com/s/b4stm4njsfls8qp/RobloxStudioLauncherBeta.exe
unzip $HOME/.piblox/wine.zip -d $HOME/wine
sudo cp $HOME/.piblox/box86 /usr/local/bin/box86
sudo mv $HOME/wine/wine /usr/local/bin/wine
rm -rf $HOME/.wine/drive_c/Program\ Files/Roblox/*
wine $HOME/.piblox/RobloxStudioLauncherBeta.exe
echo Roblox Installed!!
